# Wordpress #
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#

version: '3.2'

services:
  mysql:
    image: mysql:8.0
    container_name: ld-testing_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
    # - mysql-variables.env
    - .env
    volumes:
   # in case you want to save in specific path
      - mysqldatavolume:/var/lib/mysql  

  php-fpm:
    # build:
    #   context: ./docker/php-fpm/
    #   dockerfile: Dockerfile
    # image: link-php-fpm
    image: erenygamal12/link-php-fpm:8.0
    #Enable path conversion from Windows-style to Unix-style in volume definitions.
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql 
    restart: always
    expose:
      - 9000

  nginx:
    image: erenygamal12/link-nginx:latest
    #Enable path conversion from Windows-style to Unix-style in volume definitions.
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    volumes:
      - ./:/var/www/html
    ports:
      - '8880:80'
    depends_on:
      - php-fpm 
    restart: always   

volumes:
 mysqldatavolume:      